<?xml version="1.0" encoding="utf-8"?><Database Name="NewVisualERP" Class="VisualERPDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.99,55321;Initial Catalog=NewVisualERP;User ID=dotnet_new" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NewVisualERPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Assembly" Member="tbl_Assemblies">
    <Type Name="tbl_Assembly">
      <Column Name="AssemblyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AssemblyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_AttributesMenu" Member="tbl_AttributesMenus">
    <Type Name="tbl_AttributesMenu">
      <Column Name="AttributeMenuID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AttributeName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AttributeValue" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UnitID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IncludeOnMap" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ProcessObjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceType" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_BOM" Member="tbl_BOMs">
    <Type Name="tbl_BOM">
      <Column Name="BOMID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BomProcessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BOMLevel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BOMRevision" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UOM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StandardCost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="WorkingCost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="StdPackQty" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaxPackLength" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaxPackWidth" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaxPackHeight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ContainerQty" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MedianRelinishmentLT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MinRLT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaxRLT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Rolling12MnthUsage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AvgMonthUsage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RiskFactor" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MonthStdDevRiskFactor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KanbanQty" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InService" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="In_ServiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ObsolescenceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OnHandInventory" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OnOrder" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NextShipmentDue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NextQtyDue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartReqNxtPerd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentPurchasingOwner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrentDesignOwner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_BomProcess" Member="tbl_BomProcesses">
    <Type Name="tbl_BomProcess">
      <Column Name="BomProcessID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BomProcessName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BomParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessObjID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BomTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_BomTypeCollection" Member="tbl_BomTypeCollections">
    <Type Name="tbl_BomTypeCollection">
      <Column Name="BomTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BomTypeName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_BusinessSegment" Member="tbl_BusinessSegments">
    <Type Name="tbl_BusinessSegment">
      <Column Name="BusinessSegmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BusinessSegmentName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BusinessUnitID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_BusinessUnit" Member="tbl_BusinessUnits">
    <Type Name="tbl_BusinessUnit">
      <Column Name="BusinessUnitID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BusinessUnitName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BusinessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Bussiness" Member="tbl_Bussinesses">
    <Type Name="tbl_Bussiness">
      <Column Name="BusinessID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BusinessName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Calibration" Member="tbl_Calibrations">
    <Type Name="tbl_Calibration">
      <Column Name="CalibrationVendorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CalibrationVendorInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CalibrationVendor" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Customer" Member="tbl_Customers">
    <Type Name="tbl_Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CusPhoneNum" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CExpPlanID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CExpPlanName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DefalutAttributeMenu" Member="tbl_DefalutAttributeMenus">
    <Type Name="tbl_DefalutAttributeMenu">
      <Column Name="AttributeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AttributeName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AttributeValue" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IncludeOnMap" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UnitID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DocumentLinkType" Member="tbl_DocumentLinkTypes">
    <Type Name="tbl_DocumentLinkType">
      <Column Name="LinkTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProcessObjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LinkTypeObjectID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LinkTypeSymbol" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_HandOffData" Member="tbl_HandOffDatas">
    <Type Name="tbl_HandOffData">
      <Column Name="HOID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SytemIOID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOToID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOOutputType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HOOutputName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IncludeonMap" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HOInputID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOInputLink" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Industries" Member="tbl_Industries">
    <Type Name="tbl_Industry">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_InformationInputs" Member="tbl_InformationInputs">
    <Type Name="tbl_InformationInput">
      <Column Name="LinkID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LinkName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LinkType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IncludeOnMap" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ProcessObjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_InputType" Member="tbl_InputTypes">
    <Type Name="tbl_InputType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_InvantoryTriangle" Member="tbl_InvantoryTriangles">
    <Type Name="tbl_InvantoryTriangle">
      <Column Name="InvantoryTriangleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProcessObjID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Doller" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Time" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SourceType" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MachineList" Member="tbl_MachineLists">
    <Type Name="tbl_MachineList">
      <Column Name="MachineID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProcessObjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MachineType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MachinePhoto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PMScheduleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MTBF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MTTR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaintenanceCost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PurchasePrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BookValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RemainingLife" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ManualID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PartsListID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ParallelRelationship" Member="tbl_ParallelRelationships">
    <Type Name="tbl_ParallelRelationship">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProcessObjID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NeighbourActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PPESAnPDESA" Member="tbl_PPESAnPDESAs">
    <Type Name="tbl_PPESAnPDESA">
      <Column Name="FormID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessObjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductFeatureAdded" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FunctionofProductFeature" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ErrorEvent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ErrorEventTransferFunction" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Actions" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ActionCriticalParameter" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Conditions" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ConditonCriticalParameter" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InitialSeverity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InitialFrequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InitialDetection" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IntialRPN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Countermeasure" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CountermeasureEffectiveness" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FinalSeverity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FinalFrequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FinalDetection" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FinalRPN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cpk" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cp" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ppk" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LongtermSigma" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ShorttermSigma" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ZScore" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Sequence" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Process" Member="tbl_Processes">
    <Type Name="tbl_Process">
      <Column Name="ProcessID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProcessName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FunctionName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SystemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserRegisterID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ProcessObject" Member="tbl_ProcessObjects">
    <Type Name="tbl_ProcessObject">
      <Column Name="ProcessObjID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProcessObjName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ProcessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="XTop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YLeft" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ParallelProcessObjID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Position" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Product" Member="tbl_Products">
    <Type Name="tbl_Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductFamilyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ProductFamily" Member="tbl_ProductFamilies">
    <Type Name="tbl_ProductFamily">
      <Column Name="ProductFamilyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductFamilyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ProductLineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ProductLine" Member="tbl_ProductLines">
    <Type Name="tbl_ProductLine">
      <Column Name="ProductLineID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductLineName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Registration" Member="tbl_Registrations">
    <Type Name="tbl_Registration">
      <Column Name="RegisterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UploadPhoto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Industries" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UniqueCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_RepairLog" Member="tbl_RepairLogs">
    <Type Name="tbl_RepairLog">
      <Column Name="MachineRepairID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MachineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Critical" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TTR" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SkillTypeOfRepair" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TypeOfRepair" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ActualRepair" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CostOfRepairParts" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CostOfRepairLabor" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CostOfRepairOutsource" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Scheduled_Unscheduled" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DownTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Preventive_Predictive_Reactive" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RootCause" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Countermeasure" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Report" Member="tbl_Reports">
    <Type Name="tbl_Report">
      <Column Name="ReportID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProcessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessObjID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AttributeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReportName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ReportTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Role" Member="tbl_Roles">
    <Type Name="tbl_Role">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SubAssembly" Member="tbl_SubAssemblies">
    <Type Name="tbl_SubAssembly">
      <Column Name="SubAssemblyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AssemblyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubAssemblyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Summary" Member="tbl_Summaries">
    <Type Name="tbl_Summary">
      <Column Name="SummaryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SummaryName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ProcessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SummaryAttributeMenu" Member="tbl_SummaryAttributeMenus">
    <Type Name="tbl_SummaryAttributeMenu">
      <Column Name="SumryAttriMenuID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SumryAttriMenuName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SumryAttriMenuValue" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SummaryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IncludeOnMap" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SummaryData" Member="tbl_SummaryDatas">
    <Type Name="tbl_SummaryData">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProcessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttributeName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FunctionName" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_System" Member="tbl_Systems">
    <Type Name="tbl_System">
      <Column Name="SystemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BusinessSegmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SystemName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SystemIO" Member="tbl_SystemIOs">
    <Type Name="tbl_SystemIO">
      <Column Name="SytemIOID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FromActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ToActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SystemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SystemProcessIO" Member="tbl_SystemProcessIOs">
    <Type Name="tbl_SystemProcessIO">
      <Column Name="SysID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SystemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Target" Member="tbl_Targets">
    <Type Name="tbl_Target">
      <Column Name="TargetID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TargetName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FunctionName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SystemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserRegisterID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TargetObjects" Member="tbl_TargetObjects">
    <Type Name="tbl_TargetObject">
      <Column Name="TargetObjID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TargetObjName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TargetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="XTop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YLeft" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ParallelTargetObjID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Position" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TargetParallelRelationship" Member="tbl_TargetParallelRelationships">
    <Type Name="tbl_TargetParallelRelationship">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TargetObjID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NeighbourActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TargetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TFG" Member="tbl_TFGs">
    <Type Name="tbl_TFG">
      <Column Name="TFGID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProcessObjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tool_Fixture_GageName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TFGDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TFGVendorPart" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TFGVendor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TFGVendorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TFGCost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TFGQty" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CalibrationCycle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TimeToCailbrate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CostToCalibrate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CalibrationVendor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CalibrationVendorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CalibrationVendorInfo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CalibratedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CalibrationDate1" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CalibrationDate2" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CalibrationDate3" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CalibrationDate4" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CalibrationDate5" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TFGVendor" Member="tbl_TFGVendors">
    <Type Name="tbl_TFGVendor">
      <Column Name="TFGVendorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TFGVendor" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TypeCollection" Member="tbl_TypeCollections">
    <Type Name="tbl_TypeCollection">
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Unit" Member="tbl_Units">
    <Type Name="tbl_Unit">
      <Column Name="UnitID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Symbol" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ErrorInfos" Member="ErrorInfos">
    <Type Name="ErrorInfo">
      <Column Name="ErrorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Error" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="CycleTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CounterMeasureStrength" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CounterMeasure" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkContent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IncludeOnMap" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ProcessBlockHeader" Member="tbl_ProcessBlockHeaders">
    <Type Name="tbl_ProcessBlockHeader">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProcessId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Headerlblname" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SequanceOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteAttributeDataByID" Method="DeleteAttributeDataByID">
    <Parameter Name="AttributemenuId" Parameter="attributemenuId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteAttributeDataByProcessObjID" Method="DeleteAttributeDataByProcessObjID">
    <Parameter Name="ProcessObjId" Parameter="processObjId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteHandOffDataByID" Method="DeleteHandOffDataByID">
    <Parameter Name="HOID" Parameter="hOID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteInputDataByID" Method="DeleteInputDataByID">
    <Parameter Name="LinkID" Parameter="linkID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteInventeryProcessObjByID" Method="DeleteInventeryProcessObjByID">
    <Parameter Name="ProcessObjID" Parameter="processObjID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteMachineDataByID" Method="DeleteMachineDataByID">
    <Parameter Name="MachineID" Parameter="machineID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteMachineRepairDataByID" Method="DeleteMachineRepairDataByID">
    <Parameter Name="MachineRepairID" Parameter="machineRepairID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteMachineRepairDataByMachineID" Method="DeleteMachineRepairDataByMachineID">
    <Parameter Name="MachineID" Parameter="machineID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteParallelProcessObjDataByID" Method="DeleteParallelProcessObjDataByID">
    <Parameter Name="ProcessObjID" Parameter="processObjID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeletePPESADataByID" Method="DeletePPESADataByID">
    <Parameter Name="FormID" Parameter="formID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteProcessObjDataByID" Method="DeleteProcessObjDataByID">
    <Parameter Name="ProcessObjID" Parameter="processObjID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteReportByID" Method="DeleteReportByID">
    <Parameter Name="ReportID" Parameter="reportID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteSummaryDataByAttributeName" Method="DeleteSummaryDataByAttributeName">
    <Parameter Name="attributeName" Type="System.String" DbType="NVarChar(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteSummaryDataByProcessID" Method="DeleteSummaryDataByProcessID">
    <Parameter Name="processId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteSystemIODataByPOID" Method="DeleteSystemIODataByPOID">
    <Parameter Name="ProcessObjectID" Parameter="processObjectID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteTargetObjDataByID" Method="DeleteTargetObjDataByID">
    <Parameter Name="TargetObjID" Parameter="targetObjID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteTFGDataByID" Method="DeleteTFGDataByID">
    <Parameter Name="TFGID" Parameter="tFGID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_BulkInsertAttribute" Method="SP_BulkInsertAttribute">
    <Parameter Name="ProcessObjectID" Parameter="processObjectID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProcessID" Parameter="processID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SourceType" Parameter="sourceType" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CopyInsertBomProcess" Method="SP_CopyInsertBomProcess">
    <Parameter Name="SeletedBomProcessId" Parameter="seletedBomProcessId" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentBomProcessId" Parameter="currentBomProcessId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.udf_PutSpacesBetweenChars" Method="udf_PutSpacesBetweenChars" IsComposable="true">
    <Parameter Name="String" Parameter="string" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.DeleteErrorDataByID" Method="DeleteErrorDataByID">
    <Parameter Name="ErrorID" Parameter="errorID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>